//src/components/empresas/constants.ts
// src/components/empresas/constants.ts

export const GT_DEPARTAMENTOS = [
  "Guatemala","Sacatepéquez","Chimaltenango","Escuintla","Santa Rosa",
  "Sololá","Totonicapán","Quetzaltenango","Suchitepéquez","Retalhuleu",
  "San Marcos","Huehuetenango","Quiché","Baja Verapaz","Alta Verapaz",
  "Petén","Izabal","Zacapa","Chiquimula","Jalapa","Jutiapa","El Progreso",
] as const;

export const GT_MUNICIPIOS: Record<(typeof GT_DEPARTAMENTOS)[number], string[]> = {
  Guatemala: ["Guatemala","Mixco","Villa Nueva","San Miguel Petapa","Amatitlán"],
  Sacatepéquez: ["Antigua Guatemala","Ciudad Vieja","Sumpango"],
  Chimaltenango: ["Chimaltenango","Patzicía","Patzún"],
  Escuintla: ["Escuintla","Santa Lucía Cotzumalguapa","La Democracia"],
  "Santa Rosa": ["Cuilapa","Barberena","Santa Rosa de Lima"],
  Sololá: ["Sololá","Panajachel","San José Chacayá"],
  Totonicapán: ["Totonicapán","San Bartolo","Momostenango"],
  Quetzaltenango: ["Quetzaltenango","Olintepeque","Salcajá"],
  Suchitepéquez: ["Mazatenango","Cuyotenango","Patulul"],
  Retalhuleu: ["Retalhuleu","San Sebastián","San Felipe"],
  "San Marcos": ["San Marcos","Malacatán","San Pedro Sacatepéquez"],
  Huehuetenango: ["Huehuetenango","Barillas","La Democracia"],
  Quiché: ["Santa Cruz del Quiché","Joyabaj","Nebaj"],
  "Baja Verapaz": ["Salamá","San Miguel Chicaj"],
  "Alta Verapaz": ["Cobán","Tactic","San Pedro Carchá"],
  Petén: ["Flores","San Benito","Poptún"],
  Izabal: ["Puerto Barrios","Morales","Livingston"],
  Zacapa: ["Zacapa","Río Hondo","Teculután"],
  Chiquimula: ["Chiquimula","Esquipulas","Quezaltepeque"],
  Jalapa: ["Jalapa","San Pedro Pinula","Mataquescuintla"],
  Jutiapa: ["Jutiapa","Asunción Mita","El Progreso"],
  "El Progreso": ["Guastatoya","Sanarate","Morazán"],
};

export const BANCOS_SUGERIDOS = [
  "Banco Industrial, S.A.",
  "Banco de Desarrollo Rural, S.A. (Banrural)",
  "Banco G&T Continental, S.A.",
  "Banco Agromercantil de Guatemala, S.A.",
  "Banco Ficohsa Guatemala, S.A.",
  "Banco Inmobiliario, S.A.",
  "Banco Internacional, S.A.",
  "Banco de Antigua, S.A.",
  "Vivibanco, S.A.",
  "Banco Azteca de Guatemala, S.A.",
  "Banco de los Trabajadores",
  "Banco de América Central, S.A.",
  "Banco INV, S.A.",
  "Banco de Crédito, S.A.",
  "Banco Reformador",
];

export const LIBROS = [
  "Libro de Compras","Libro de Ventas","Libro Diario","Libro Mayor",
  "Estados Financieros","Libro de Caja","Libro de Inventario",
  "Libro de Cuentas Corrientes","Libro de Planillas","Libro de Mayor General",
  "Libro de Registros Auxiliares","Libro Diario (Resumen)",
];

/** ===== Catálogo SAT - Actividad económica ===== */
export type ActividadSat = { codigo: string; descripcion: string };

export const ACTIVIDADES_SAT: ActividadSat[] = [
  { codigo: "0500.01", descripcion: "PESCADO" },
  { codigo: "0500.02", descripcion: "CAMARÓN" },
  { codigo: "1010.00", descripcion: "EXTRACCIÓN DE CARBÓN Y LIGNITO; EXTRACCIÓN DE TURBA" },
  { codigo: "1020.00", descripcion: "EXTRACCIÓN Y AGLOMERACIÓN DE CARBÓN DE PIEDRA" },
  { codigo: "1030.00", descripcion: "EXTRACCIÓN Y AGLOMERACIÓN DE LIGNITO" },
  { codigo: "1040.00", descripcion: "EXTRACCIÓN Y AGLOMERACIÓN DE TURBA" },
  { codigo: "1110.00", descripcion: "EXTRACCIÓN DE PETRÓLEO CRUDO Y GAS NATURAL; ACTIVIDADES DE SERVICIO (EXCEPTO PROSPECCIÓN)" },
  { codigo: "1120.00", descripcion: "EXTRACCIÓN DE PETRÓLEO CRUDO Y GAS NATURAL" },
  { codigo: "1130.00", descripcion: "SERVICIOS RELACIONADOS CON LA EXTRACCIÓN DE PETRÓLEO Y GAS (EXCEPTO PROSPECCIÓN)" },
  { codigo: "1200.00", descripcion: "EXTRACCIÓN DE MINERALES DE URANIO Y TORIO" },
  { codigo: "1310.00", descripcion: "EXTRACCIÓN DE MINERALES METALÍFEROS" },
  { codigo: "1320.00", descripcion: "EXTRACCIÓN DE MINERALES DE HIERRO" },
  { codigo: "1330.00", descripcion: "EXTRACCIÓN DE MINERALES METALÍFEROS NO FERROSOS (EXCEPTO URANIO Y TORIO)" },
  { codigo: "1410.00", descripcion: "EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS" },
  { codigo: "1421.00", descripcion: "EXTRACCIÓN DE PIEDRA, ARENA Y ARCILLA" },
  { codigo: "1422.00", descripcion: "EXTRACCIÓN DE MINERALES PARA FABRICACIÓN DE ABONOS Y PRODUCTOS QUÍMICOS" },
  { codigo: "1429.00", descripcion: "EXTRACCIÓN DE SAL" },
  { codigo: "1511.00", descripcion: "EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS, NO CLASIFICADAS EN OTRA PARTE" },
  { codigo: "1512.00", descripcion: "ELABORACIÓN DE PRODUCTOS ALIMENTICIOS Y BEBIDAS" },
  { codigo: "1513.01", descripcion: "PRODUCCIÓN, PROCESAMIENTO Y CONSERVACIÓN DE CARNE Y PRODUCTOS CÁRNICOS" },
  { codigo: "1513.02", descripcion: "ELABORACIÓN Y CONSERVACIÓN DE PESCADO Y PRODUCTOS DE PESCADO" },
  { codigo: "1513.03", descripcion: "ELABORACIÓN Y CONSERVACIÓN DE FRUTAS, LEGUMBRES Y HORTALIZAS" },
  { codigo: "1514.00", descripcion: "LEGUMBRES CONGELADAS Y EN CONSERVA" },
  { codigo: "1515.00", descripcion: "JUGOS DE FRUTAS Y DE LEGUMBRES" },
  { codigo: "1519.01", descripcion: "FRUTAS PREPARADAS O CONSERVADAS" },
  { codigo: "1519.02", descripcion: "OTRAS FRUTAS, LEGUMBRES Y CONSERVAS, NO CLASIFICADAS EN OTRA PARTE" },
  { codigo: "1520.00", descripcion: "ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN VEGETAL Y ANIMAL" },
  { codigo: "1531.00", descripcion: "ELABORACIÓN DE PRODUCTOS LÁCTEOS" },
  { codigo: "1532.00", descripcion: "ELABORACIÓN DE PRODUCTOS DE MOLINERÍA" },
  { codigo: "1533.00", descripcion: "ELABORACIÓN DE ALMIDONES Y DERIVADOS DEL ALMIDÓN" },
  { codigo: "1541.00", descripcion: "ELABORACIÓN DE ALIMENTOS PREPARADOS PARA ANIMALES" },
  { codigo: "1542.00", descripcion: "ELABORACIÓN DE PRODUCTOS DE PANADERÍA" },
  { codigo: "1543.01", descripcion: "ELABORACIÓN DE AZÚCAR" },
  { codigo: "1543.02", descripcion: "AZÚCAR DE CAÑA REFINADA" },
  { codigo: "1543.03", descripcion: "AZÚCAR DE CAÑA SIN REFINAR" },
  { codigo: "1543.04", descripcion: "MELAZA" },
  { codigo: "1543.99", descripcion: "OTROS PRODUCTOS DE LA CAÑA DE AZÚCAR, NO CLASIFICADOS EN OTRA PARTE" },
  { codigo: "1544.00", descripcion: "ELABORACIÓN DE CACAO Y CHOCOLATE Y DE PRODUCTOS DE CONFITERÍA" },
  { codigo: "1549.00", descripcion: "ELABORACIÓN DE MACARRONES, FIDEOS Y PRODUCTOS FARINÁCEOS" },
  { codigo: "1551.00", descripcion: "ELABORACIÓN DE OTROS PRODUCTOS ALIMENTICIOS, N.C.O.P." },
  { codigo: "1552.00", descripcion: "DESTILACIÓN/RECTIFICACIÓN DE BEBIDAS ALCOHÓLICAS; PRODUCCIÓN DE ALCOHOL ETÍLICO" },
  { codigo: "1553.00", descripcion: "ELABORACIÓN DE VINOS" },
  { codigo: "1554.00", descripcion: "ELABORACIÓN DE BEBIDAS MALTEADAS Y DE MALTA" },
  { codigo: "1600.00", descripcion: "ELABORACIÓN DE BEBIDAS NO ALCOHÓLICAS; PRODUCCIÓN DE AGUAS MINERALES" },
  { codigo: "1711.00", descripcion: "FABRICACIÓN DE PRODUCTOS DE TABACO" },
  { codigo: "1712.00", descripcion: "FABRICACIÓN DE PRODUCTOS TEXTILES" },
  { codigo: "1721.00", descripcion: "PREPARACIÓN E HILATURA DE FIBRAS TEXTILES; TEJEDURA" },
  { codigo: "1722.00", descripcion: "ACABADO DE PRODUCTOS TEXTILES" },
  { codigo: "1723.00", descripcion: "FABRICACIÓN DE ARTÍCULOS CONFECCIONADOS DE TEXTIL, EXCEPTO PRENDAS" },
  { codigo: "1729.00", descripcion: "FABRICACIÓN DE TAPICES Y ALFOMBRAS" },
  { codigo: "1730.00", descripcion: "FABRICACIÓN DE CUERDAS, CORDELERÍA, BRAMANTES Y REDES" },
  { codigo: "1810.00", descripcion: "FABRICACIÓN DE OTROS PRODUCTOS TEXTILES, N.C.O.P." },
  { codigo: "1820.00", descripcion: "FABRICACIÓN DE TEJIDOS Y ARTÍCULOS DE PUNTO Y GANCHILLO" },
  { codigo: "1911.00", descripcion: "FABRICACIÓN DE PRENDAS DE VESTIR; ADOBO Y TEÑIDO DE PIELES" },
  { codigo: "1920.00", descripcion: "FABRICACIÓN DE PRENDAS DE VESTIR, EXCEPTO PRENDAS DE PIEL" },
  { codigo: "2010.00", descripcion: "ADOBO Y TEÑIDO DE PIELES; FABRICACIÓN DE ARTÍCULOS DE PIEL" },
  { codigo: "2021.00", descripcion: "CURTIDO Y ADOBO DE CUEROS; MALETAS/BOLSOS/ARTÍCULOS TALABARTERÍA Y CALZADO" },
  { codigo: "2022.00", descripcion: "CURTIDO Y ADOBO DE CUEROS" },
  { codigo: "2023.00", descripcion: "FABRICACIÓN DE MALETAS/BOLSOS/ARTÍCULOS SIMILARES, Y TALABARTERÍA" },
  { codigo: "2029.00", descripcion: "FABRICACIÓN DE CALZADO" },
  { codigo: "2101.00", descripcion: "FABRICACIÓN DE PRODUCTOS DE MADERA Y CORCHO (EXCEPTO MUEBLES)" },
  { codigo: "2102.00", descripcion: "ASERRADO Y ACEPILLADURA DE MADERA" },
  { codigo: "2103.00", descripcion: "FABRICACIÓN DE HOJAS PARA CHAPADO; CONTRACHAPADOS/PANELES" },
  // …………………………………… Pega aquí el resto de filas del catálogo tal como me las enviaste ……………………………………
  { codigo: "9999.99", descripcion: "EXTRANJERO DIPLOMÁTICO O AGENTE DE ORGANISMO INT." },
  { codigo: "0000.00", descripcion: "ESTUDIANTE" },
];

export const actividadPorCodigo = (codigo?: string) =>
  ACTIVIDADES_SAT.find((a) => a.codigo === codigo);
